// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEP_rcockes_5tER6XuGUWwjGDSUmXI-8',
    appId: '1:363266365725:web:9761d1f0738eccd77c29f4',
    messagingSenderId: '363266365725',
    projectId: 'shoes-appdata',
    authDomain: 'shoes-appdata.firebaseapp.com',
    storageBucket: 'shoes-appdata.appspot.com',
    measurementId: 'G-12F5XDHM84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBICuQZ174jv3N-N5W38KFR_dwttQzyOoU',
    appId: '1:363266365725:android:aa91141951f2e4127c29f4',
    messagingSenderId: '363266365725',
    projectId: 'shoes-appdata',
    storageBucket: 'shoes-appdata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5A7napvNFHbtkY01UIMJJ-Me0lgF5gfU',
    appId: '1:363266365725:ios:be78e35afef53ab37c29f4',
    messagingSenderId: '363266365725',
    projectId: 'shoes-appdata',
    storageBucket: 'shoes-appdata.appspot.com',
    iosBundleId: 'com.example.cat3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5A7napvNFHbtkY01UIMJJ-Me0lgF5gfU',
    appId: '1:363266365725:ios:be78e35afef53ab37c29f4',
    messagingSenderId: '363266365725',
    projectId: 'shoes-appdata',
    storageBucket: 'shoes-appdata.appspot.com',
    iosBundleId: 'com.example.cat3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEP_rcockes_5tER6XuGUWwjGDSUmXI-8',
    appId: '1:363266365725:web:fee410de8b0252837c29f4',
    messagingSenderId: '363266365725',
    projectId: 'shoes-appdata',
    authDomain: 'shoes-appdata.firebaseapp.com',
    storageBucket: 'shoes-appdata.appspot.com',
    measurementId: 'G-J86DW65QCS',
  );
}
